"""initial schema

Revision ID: 8657e8420c51
Revises: 
Create Date: 2026-03-22 02:35:50.392132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8657e8420c51'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cron_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedules_found', sa.Integer(), nullable=False),
    sa.Column('notifications_sent', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('letter_series', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('number_range_start', sa.Integer(), nullable=False),
    sa.Column('number_range_end', sa.Integer(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registration_deadline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vehicle_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desired_number', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmation_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unsubscribe_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confirmation_expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('confirmation_token'),
    sa.UniqueConstraint('email', 'vehicle_type', 'desired_number', name='idx_sub_email_vt_num'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['subscriber_id'], ['subscribers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subscriber_id', 'schedule_id', name='uq_notification')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('subscribers')
    op.drop_table('schedules')
    op.drop_table('cron_runs')
    # ### end Alembic commands ###
